# Site settings
title: Test Laure
email: laure@leetchi.com
description: > # this means to ignore newlines until "baseurl:"
  Test Laure
baseurl: "/PageTest/" # the subpath of your site, e.g. /blog/
url: "http://zazoun.github.io/PageTest/" # the base hostname & protocol for your site
twitter_username: Zazoun
github_username:  zazoun

# Build settings
markdown: kramdown
